doodle/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.urls import views as auth_views
from illustrations import views as illustration_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('illustrations.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('images/<str:image_name>/', illustration_views.serve_image, name='serve_image'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

illustrations/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('artists/', views.artists, name="artists"),
    path('contact/', views.contact, name="contact"),
    path('illustrations/', views.illustrations, name="illustrations"),
    path('create_doodle/', views.create_doodle, name="create_doodle"),
    path('<int:doodle_id>/delete/doodle_confirm_delete/', views.delete_doodle, name="delete_doodle"),
    path('register/', views.register, name="register"),
    path('profile/', views.profile, name='profile')
]

illustrations/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class PostDoodle(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='photos/', blank=False, null=False)
    text = models.TextField(max_length=40)

def __str__(self):
    return f'{self.user.username} - {self.text[:10]}'

illustrations/forms.py
from django import forms
from .models import PostDoodle
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class PostDoodleForm(forms.ModelForm):
    class Meta:
        model = PostDoodle
        fields = ['photo', 'text']

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('username', 'email', 'password1','password2')

illustrations/views.py
from django.shortcuts import render
from .models import PostDoodle
from .forms import PostDoodleForm, UserRegistrationForm
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.http import FileResponse, Http404
from django.conf import settings
import os

# Create your views here.
def home(request):
    return render(request, 'illustrations/index.html')

def artists(request):
    return render(request, 'illustrations/artists.html')

def contact(request):
    return render(request, 'illustrations/contact.html')

def illustrations(request):
    post_doodle = PostDoodle.objects.all()
    return render(request, 'illustrations/illustrations.html', {'post_doodle': post_doodle})

@login_required
def create_doodle(request):
    if request.method == "POST":
        form = PostDoodleForm(request.POST, request.FILES)
        if form.is_valid():
            post_doodle = form.save(commit=False)
            post_doodle.user = request.user
            post_doodle.save()
            return redirect('illustrations')
    else:
        form = PostDoodleForm()
    return render(request, 'illustrations/create_doodle.html', {'form': form})

@login_required
def delete_doodle(request, doodle_id):
    post_doodle = get_object_or_404(PostDoodle, pk=doodle_id, user=request.user)
    if request.method == "POST":
        post_doodle.delete()
        return redirect('illustrations')
    return render(request, 'illustrations/doodle_confirm_delete.html', {'post_doodle': post_doodle})

def register(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.save()
            login(request, user)
            return redirect('home')
    else:
        form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'form': form})

@login_required
def profile(request):
    return render(request, 'profile.html', {'user': request.user})

@login_required
def serve_image(request, image_name):
    file_path = os.path.join(settings.MEDIA_ROOT, 'photos', image_name)
    if os.path.exists(file_path):
        return FileResponse(open(file_path, 'rb'), content_type='image/jpeg')
    raise Http404("Image does not exist")

illustrations/templates/illustrations/artists.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Doodle - Artists
{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand text-black" href="/">Doodle</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-black" aria-current="page" href="{% url 'illustrations' %}">Illustrations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-black" href="{% url 'artists' %}">Artists</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger mx-2" type="submit">Logout</button>
      </form>
      {% else %}
      <a class="btn btn-outline-success" style="margin-right: 8px;" href="{% url 'register' %}">Sign up</a>
      <a class="btn btn-success" href="{% url 'login' %}">Login</a>
      {% endif %}
    </div>
  </div>
</nav>

<h1 class="text-black text-center">This is Artists Page</h1>
<h1 class="text-black text-center">This is Artists Page</h1>
<h1 class="text-black text-center">This is Artists Page</h1>
<h1 class="text-black text-center">This is Artists Page</h1>
<h1 class="text-black text-center">This is Artists Page</h1>

<hr>
<div class="blockcode">

  <footer class="page-footer text-black">
    <div class="d-flex flex-column mx-auto py-5" style="width: 70%">
      <div class="d-flex flex-wrap justify-content-between">
        <div class="align-self-center">
          <a href="/#" class="d-flex align-items-center p-0 text-black" style="text-decoration: none;">
            <span class="h5 font-weight-bold text-black" style="margin-bottom: 160px;">Doodle</span>
          </a>
        </div>
        <div>
          <p class="h5 mb-4" style="font-weight: 600">Get to know us</p>
          <ul class="p-0" style="list-style: none; cursor: pointer">
            <li class="my-2">
              <a class="text-black" href="{% url 'illustrations' %}" style="text-decoration: none;">Illustrations</a>
            </li>
            <li class="my-2">
              <a class="text-black" href="/" style="text-decoration: none;">Blog</a>
            </li>
            <li class="my-2">
              <a class="text-black" href="{% url 'artists' %}" style="text-decoration: none;">Artists</a>
            </li>
          </ul>
        </div>
        <div>
          <p class="h5 mb-4" style="font-weight: 600">Help</p>
          <ul class="p-0" style="list-style: none; cursor: pointer">
            <li class="my-2">
              <a class="text-black" href="{% url 'contact' %}" style="text-decoration: none;">Contact</a>
            </li>
            <li class="my-2">
              <a class="text-black" href="{% url 'register' %}" style="text-decoration: none;">Sign Up</a>
            </li>
            <li class="my-2">
              <a class="text-black" href="{% url 'login' %}" style="text-decoration: none;">Login</a>
            </li>
          </ul>
        </div>
        <div>
          <p class="h5 mb-4" style="font-weight: 600">Stay in touch</p>
          <ul class="p-0" style="list-style: none; cursor: pointer">
            <li class="my-2">
              <a class="text-black" href="/" style="text-decoration: none;">Discord</a>
            </li>
            <li class="my-2">
              <a class="text-black" href="/" style="text-decoration: none;">Instagram</a>
            </li>
          </ul>
        </div>
      </div>
      <small class="text-center mt-5">&copy; Doodle, 2024. All rights reserved.</small>
    </div>
  </footer>
</div>

{% endblock %}

illustrations/templates/illustrations/contact.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Doodle - Contact
{% endblock %}

{% block style %}
<style>
    .formm { max-width:420px; margin:50px auto; }

.formm {
    margin-top: 120px;
}

.feedback-input {
  color:white;
  font-weight:500;
  font-size: 18px;
  border-radius: 5px;
  line-height: 22px;
  background-color: transparent;
  border:2px solid #198754;
  transition: all 0.3s;
  padding: 13px;
  margin-bottom: 15px;
  width: 90%;
  box-sizing: border-box;
  outline:0;
}

.feedback-input:focus { border:2px solid #146c43; }

textarea {
  height: 150px;
  line-height: 150%;
  resize:vertical;
}

.button {
  width: 90%;
  background:#198754;
  border-radius:5px;
  border:0;
  text-align: center;
  cursor:pointer;
  color:white;
  font-size:24px;
  padding-top:10px;
  padding-bottom:10px;
  transition: all 0.3s;
  margin-top:-4px;
  font-weight:700;
}
.button:hover { background:#146c43; }

::-webkit-scrollbar {
width: 3px;
}

::-webkit-scrollbar-track {
background: #fff;
}

::-webkit-scrollbar-thumb {
background: #198754;
border-radius: 10px;
}
</style>
{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand text-black" href="/">Doodle</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-black" aria-current="page" href="{% url 'illustrations' %}">Illustrations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-black" href="{% url 'artists' %}">Artists</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger mx-2" type="submit">Logout</button>
      </form>
      {% else %}
      <a class="btn btn-outline-success" style="margin-right: 8px;" href="{% url 'register' %}">Sign up</a>
      <a class="btn btn-success" href="{% url 'login' %}">Login</a>
      {% endif %}
    </div>
  </div>
</nav>



<form class="text-center formm">      
  <h1 class="text-black text-center">Contact Team</h1>
  <p class="text-black text-center">Want to report a bug? Want more information about services? Let the team know about it and we will get back to you as soon as possible!</p>
    <input name="name" type="text" class="feedback-input" placeholder="Name" />   
    <input name="email" type="text" class="feedback-input" placeholder="Email" />
    <textarea name="text" class="feedback-input" placeholder="Comment"></textarea>
    <input class="button" value="SUBMIT"/>
  </form>

  <hr>
  <div class="blockcode">
  
    <footer class="page-footer text-black">
      <div class="d-flex flex-column mx-auto py-5" style="width: 70%">
        <div class="d-flex flex-wrap justify-content-between">
          <div class="align-self-center">
            <a href="/#" class="d-flex align-items-center p-0 text-black" style="text-decoration: none;">
              <span class="h5 font-weight-bold text-black" style="margin-bottom: 160px;">Doodle</span>
            </a>
          </div>
          <div>
            <p class="h5 mb-4" style="font-weight: 600">Get to know us</p>
            <ul class="p-0" style="list-style: none; cursor: pointer">
              <li class="my-2">
                <a class="text-black" href="{% url 'illustrations' %}" style="text-decoration: none;">Illustrations</a>
              </li>
              <li class="my-2">
                <a class="text-black" href="/" style="text-decoration: none;">Blog</a>
              </li>
              <li class="my-2">
                <a class="text-black" href="{% url 'artists' %}" style="text-decoration: none;">Artists</a>
              </li>
            </ul>
          </div>
          <div>
            <p class="h5 mb-4" style="font-weight: 600">Help</p>
            <ul class="p-0" style="list-style: none; cursor: pointer">
              <li class="my-2">
                <a class="text-black" href="{% url 'contact' %}" style="text-decoration: none;">Contact</a>
              </li>
              <li class="my-2">
                <a class="text-black" href="{% url 'register' %}" style="text-decoration: none;">Sign Up</a>
              </li>
              <li class="my-2">
                <a class="text-black" href="{% url 'login' %}" style="text-decoration: none;">Login</a>
              </li>
            </ul>
          </div>
          <div>
            <p class="h5 mb-4" style="font-weight: 600">Stay in touch</p>
            <ul class="p-0" style="list-style: none; cursor: pointer">
              <li class="my-2">
                <a class="text-black" href="/" style="text-decoration: none;">Discord</a>
              </li>
              <li class="my-2">
                <a class="text-black" href="/" style="text-decoration: none;">Instagram</a>
              </li>
            </ul>
          </div>
        </div>
        <small class="text-center mt-5">&copy; Doodle, 2024. All rights reserved.</small>
      </div>
    </footer>
  </div>

{% endblock %}

illustrations/templates/illustrations/create_doodle.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Doodle - Create
{% endblock %}


{% block content %}

<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand text-black" href="/">Doodle</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-black" aria-current="page" href="{% url 'illustrations' %}">Illustrations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-black" href="{% url 'artists' %}">Artists</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger mx-2" type="submit">Logout</button>
      </form>
      {% else %}
      <a class="btn btn-outline-success" style="margin-right: 8px;" href="{% url 'register' %}">Sign up</a>
      <a class="btn btn-success" href="{% url 'login' %}">Login</a>
      {% endif %}
    </div>
  </div>
</nav>

<h2 class="text-black text-center flex-column" >
  {%if form.instance.pk %}
  Edit Doodle
  {% else %}
  Post a Doodle
  {% endif %}
  <form method="post" enctype="multipart/form-data" style="margin-top: 80px;" class="form">
    {% csrf_token %}
    {{ form }}
    <button class="btn btn-primary btn-lg" type="submit">Submit</button>
  </form>
</h2>

{% endblock %}

illustrations/templates/illustrations/doodle_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Doodle - Delete
{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand text-black" href="/">Doodle</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-black" aria-current="page" href="{% url 'illustrations' %}">Illustrations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-black" href="{% url 'artists' %}">Artists</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger mx-2" type="submit">Logout</button>
      </form>
      {% else %}
      <a class="btn btn-outline-success" style="margin-right: 8px;" href="{% url 'register' %}">Sign up</a>
      <a class="btn btn-success" href="{% url 'login' %}">Login</a>
      {% endif %}
    </div>
  </div>
</nav>

<h1 class="text-black text-center" style="margin-top: 150px;">Are you sure that you want to delete this Post?</h1>
<form method="post" class="text-center" style="margin-top: 5px;">
  {% csrf_token %}
  <button class="btn btn-danger btn-lg">Delete</button>
  <a class="btn btn-success btn-lg" href="{% url 'illustrations' %}">Cancel</a>
</form>

{% endblock %}

illustrations/templates/illustrations/illustrations.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Doodle - Illustrations
{% endblock %}

{% block content %}

<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand text-black" href="/">Doodle</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-black" aria-current="page" href="{% url 'illustrations' %}">Illustrations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-black" href="{% url 'artists' %}">Artists</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
      <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-danger mx-2" type="submit">Logout</button>
      </form>
      {% else %}
      <a class="btn btn-outline-success" style="margin-right: 8px;" href="{% url 'register' %}">Sign up</a>
      <a class="btn btn-success" href="{% url 'login' %}">Login</a>
      {% endif %}
    </div>
  </div>
</nav>

  <h1 class="text-black" style="position: relative; left: 100px; top: 100px; width: 500px;">All Doodles</h1>
  <p class="text-black" style="position: relative; left: 100px; top: 100px; width: 500px;">These all are masterpieces made by artists around the world</p>
  <a href="{% url 'create_doodle' %}" class="btn btn-success" style="position: relative; left: 100px; top: 100px;">Post a Doodle</a>

  <main style=" max-width: 1200px; margin: 30px auto; padding: 0 20px; width: 100%; display: grid; grid-auto-rows: 450px; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); grid-gap: 1em;">
    #{% for doodle in post_doodle %}
    {{doodle.photo.url}}
    <div style="border-radius: 10px; padding: 10px; color: #000; border: 1px solid #dbdbdb; transition: transform 0.2s ease; cursor: pointer; margin-top: 100px;" onmouseover="this.style.transform='translateY(-5px)';" onmouseout="this.style.transform='translateY(0px)';">
      <img src="{{doodle.photo.url}}" style="height: 200px; display: block; margin: auto;">
      <h5>{{doodle.user.username}}</h5>
      <p class="mb-2">{{doodle.text}}</p>
      {% if doodle.user == user %}
      <a href="{% url 'delete_doodle' doodle.id %}" type="button" class="btn btn-danger" style="position: relative; top: 10px;">Delete</a>
      {% endif %}
    </div>
    {% endfor %}
  </main>

  

{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap" rel="stylesheet">
    <title>
      {% block title %}
      Doodle
      {% endblock %}
    </title>

    {% block style %}

    <style>
      ::-webkit-scrollbar {
width: 3px;
}

::-webkit-scrollbar-track {
background: #fff;
}

::-webkit-scrollbar-thumb {
background: #198754;
border-radius: 10px;
}

  </style>

    {% endblock %}

</head>
<body>
    {% block content %}

    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Doodle - User Profile
{% endblock %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block content %}
<div class="auth-container">
    <h2 class="auth-title">User Profile</h2>
    <div class="profile-info">
        <p><strong>Username:</strong> {{ user.username }}</p>
        <p><strong>Email:</strong> {{ user.email }}</p>
    </div>
    <h3>My Doodles</h3>
    <div class="user-doodles">
        {% for doodle in user.postdoodle_set.all %}
            <div class="doodle-item">
                <img src="{% url 'serve_image' image_name=doodle.photo.name %}" alt="{{ doodle.text }}">
                <p>{{ doodle.text }}</p>
            </div>
        {% empty %}
            <p>You haven't created any doodles yet.</p>
        {% endfor %}
    </div>
    <a href="{% url 'create_doodle' %}" class="btn btn-primary">Create New Doodle</a>
</div>
{% endblock %}